application: bseu-api
version: 2-0
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: /static/img/favicon.ico
  upload: /static/img/favicon\.ico

- url: /css
  static_dir: css

- url: /scripts
  static_dir: scripts

- url: /static/img
  static_dir: static/img

- url: /static/js
  static_dir: static/js

- url: /static/css
  static_dir: static/css

- url: /images
  static_dir: images

- url: /task/.*
  script: dispatch.tasks_app
  login: admin

- url: .*
  script: dispatch.site_app

libraries:
- name: lxml
  version: latest

builtins:
- appstats: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
