application: bseu-api
version: 2-0
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: /static/img/favicon.ico
  upload: /static/img/favicon\.ico

- url: /css
  static_dir: css

- url: /scripts
  static_dir: scripts

- url: /static/img
  static_dir: static/img

- url: /static/js
  static_dir: static/js

- url: /static/css
  static_dir: static/css

- url: /images
  static_dir: images

- url: /auth
  script: auth.app

- url: /calendar_auth
  script: auth.app

- url: /link/.*
  script: resolver.app

- url: /importer
  script: calendar.app
  
- url: /fetch_schedules
  script: calendar.app
  login: admin

- url: /create_events
  script: calendar.app
  login: admin

- url: /maintenance
  script: maintenance.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: lxml
  version: latest

- name: webapp2
  version: "2.5.1"

builtins:
- appstats: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
